spring:
  application:
    name: AppointmentService

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 16032005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example.customerservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

server:
  port: 9197

customer-service:
  url: http://localhost:9194

business-service:
  url: http://localhost:9195
